### ISSUE TITLE
Config not correctly parsing aws credentials file in python 3.5

### ISSUE THREAD

**Issue by asgoel** [boto/boto#3474] opened 2016-01-26 02:21 UTC
Looks like there is some issue with how the custom `Config` class is overriding the `ConfigParser` class in python 3.5.1 on Mac OSX 10.10.5. I am not able to read my aws credentials from the default `~/.aws/credentials` file if I use the boto `Config` class, but am able to if I use the `boto.compat.ConfigParser` class.

```
Python 3.5.1 (v3.5.1:37a07cee5969, Dec  5 2015, 21:12:44)
[GCC 4.2.1 (Apple Inc. build 5666) (dot 3)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from boto.compat import ConfigParser
>>> c = ConfigParser()
>>> c.read("/Users/asgoel/.aws/credentials")
['/Users/asgoel/.aws/credentials']
>>> c.get("default", "aws_access_key_id")
RETURNS_AWS_ACCESS_KEY
>>> from boto.pyami.config import Config
>>> c1 = Config()
c1.read("/Users/ashu/.aws/credentials")
['/Users/ashu/.aws/credentials']
>>> print(c1.get("default", "aws_access_key_id"))
None
```

Makes running applications locally a little bit annoying but not a huge issue, just something I thought I would point out to see if anyone is having similar problems. I couple of others within my organization are facing the same problem.

**Comment by farvour** [comment] 2016-02-01 22:52
I too, am experiencing this issue. Is there a proposed fix and ETA?

**Comment by jvkersch** [comment] 2016-02-16 13:45
I just spent some time debugging this issue after encountering it, too (I should have checked the issues first). It looks like Python 3.5. adds some default options to the `get` method of the `ConfigParser` class, and these confuse boto's `Config` (which derives from `ConfigParser`). For the record, here is a minimal example that will reproduce the issue 
```python
from configparser import ConfigParser


class Config(ConfigParser):

    def __init__(self):
        ConfigParser.__init__(self)

    def get(self, section, name, default=None):
        try:
            val = ConfigParser.get(self, section, name)
        except:
            val = default
        return val


c = Config()
c['FOO'] = {}
c['FOO']['bar'] = 'baz'

assert c.get('FOO', 'bar') == 'baz'
```
Internally, the call to `ConfigParser.get` raises a `TypeError` because of the aforementioned extra arguments, but this gets swallowed by the catch-all try/except around it so that `None` always gets returned.

I think the fix would be to add the new default arguments to the methods on boto's `Config` class, but I haven't tried this out. Also, it would probably be good to turn the blanket `except:` into an `except KeyError`.

**Comment by tsavola** [comment] 2016-02-18 14:00
I just debugged the issue, and arrived at the same conclusion. However, I think this should be fixed by replacing the inheritance with composition:

```
--- a/boto/pyami/config.py
+++ b/boto/pyami/config.py
@@ -49,12 +49,12 @@ elif 'BOTO_PATH' in os.environ:
         BotoConfigLocations.append(expanduser(path))
 
 
-class Config(ConfigParser):
+class Config(object):
 
     def __init__(self, path=None, fp=None, do_load=True):
         # We don't use ``super`` here, because ``ConfigParser`` still uses
         # old-style classes.
-        ConfigParser.__init__(self, {'working_dir': '/mnt/pyami',
+        self._impl = ConfigParser({'working_dir': '/mnt/pyami',
                                          'debug': '0'})
         if do_load:
             if path:
@@ -70,6 +70,9 @@ class Config(ConfigParser):
                 except IOError:
                     warnings.warn('Unable to load AWS_CREDENTIAL_FILE (%s)' % full_path)
 
+    def __getattr__(self, name):
+        return getattr(self._impl, name)
+
     def load_credential_file(self, path):
         """Load a credential file as is setup like the Java utilities"""
         c_data = StringIO()
@@ -139,21 +142,21 @@ class Config(ConfigParser):
 
     def get(self, section, name, default=None):
         try:
-            val = ConfigParser.get(self, section, name)
+            val = self._impl.get(section, name)
         except:
             val = default
         return val
 
     def getint(self, section, name, default=0):
         try:
-            val = ConfigParser.getint(self, section, name)
+            val = self._impl.getint(section, name)
         except:
             val = int(default)
         return val
 
     def getfloat(self, section, name, default=0.0):
         try:
-            val = ConfigParser.getfloat(self, section, name)
+            val = self._impl.getfloat(section, name)
         except:
             val = float(default)
         return val
```

**Comment by tsavola** [comment] 2016-02-18 14:03
(Of course the naked ```except```s should also be changed, but I didn't do it since it wasn't necessary to demonstrate the fix.)

**Comment by jvkersch** [comment] 2016-02-18 14:03
> I think this should be fixed by replacing the inheritance with composition:

I agree, that is the way to go.

**Closed** 2016-04-04 19:34 UTC
