### ISSUE TITLE
Any maintainers?

### ISSUE THREAD

**Issue by stevenbrichards** [boto/boto#3302] opened 2015-08-17 04:22 UTC
Noticed the last PR was merged in early July, is this repo in need of more maintainers? looks like there are lots of issues that haven't been tagged or looked at much.

**Comment by kyleknap** [comment] 2015-08-19 01:13
Yes, while our attention on boto has not been as consistent as we wanted to, we do plan to continue maintaining boto for the foreseeable future. We do welcome and appreciate any help we can get from the community towards the upkeep of boto. I recently updated the [Contribution](https://github.com/boto/boto/pull/3307) guidelines on how you can help (past opening issues and pull requests). Taking on tasks like the ones listed in the Maintenance section would really help individuals with write access because the actual action of adding a label, closing an issue, or clicking the merge button for pull requests is fast, it is the tasks leading up to those actions that may take a significant amount of time (e.g. determining the appropriate label, reproducing issues, and reviewing pull requests).

**Comment by stevenbrichards** [comment] 2015-08-19 01:45
I'm interested in helping with maintenance, triaging, and PR review. Might be helpful if I could at least add labels to show it's been looked at and triaged.

**Comment by kyleknap** [comment] 2015-08-19 17:51
That is great to hear. So I looked into trying to set up a permissions group on GitHub such that members only have access to tag issues, but I was not able to find that level of granularity (I only saw read, write, and admin access). So maybe for now, you can comment with the labels that you think that should be added such as:
```
Labels: Bug, Confirmed, S3
```
then I or somebody else with permissions can go back and add the appropriate labels based on what you commented.

For an idea of what the labels mean, I would look at some of the labels that we have placed on pull requests.

Let me know if you have any more questions.

**Comment by stevenbrichards** [comment] 2015-08-19 17:54
Will do! Also, something that may be useful for you/boto (and something I could use to help triage) is [ZenHub](zenhub.io), it's a chrome extension that injects kanban style boards into github so we could create pipelines for triage, WIP, etc. and I could move things between pipelines to assist.

full disclosure, I work on ZenHub.io

**Closed** 2015-08-19 21:36 UTC
